
;; Taken from https://gist.github.com/mordocai/50783defab3c3d1650e068b4d1c91495

;;; Fira code
;; This works when using emacs --daemon + emacsclient
(add-hook 'after-make-frame-functions (lambda (frame) (set-fontset-font t '(#Xedff . #Xee6c) "icons-in-terminal")))
;; This works when using emacs without server/client
(set-fontset-font t '(#Xedff . #Xee6e) "icons-in-terminal")
;; I haven't found one statement that makes both of the above situations work, so I use both for now

(defconst fira-code-font-lock-keywords-alist
  (mapcar (lambda (regex-char-pair)
            `(,(car regex-char-pair)
              (0 (prog1 ()
                   (compose-region (match-beginning 1)
                                   (match-end 1)
                                   ;; The first argument to concat is a string containing a literal tab
                                   ,(concat "	" (list (decode-char 'ucs (cadr regex-char-pair)))))))))
          '(("\\(www\\)"                   #Xedff)
            ("[^/]\\(\\*\\*\\)[^/]"        #Xee00)
            ("\\(\\*\\*\\*\\)"             #Xee01)
            ("\\(\\*\\*/\\)"               #Xee02)
            ("\\(\\*>\\)"                  #Xee03)
            ("[^*]\\(\\*/\\)"              #Xee04)
            ("\\(\\\\\\\\\\)"              #Xee05)
            ("\\(\\\\\\\\\\\\\\)"          #Xee06)
            ("\\({-\\)"                    #Xee07)
            ("\\(\\[\\]\\)"                #Xee08)
            ("\\(::\\)"                    #Xee09)
            ("\\(:::\\)"                   #Xee0a)
            ("[^=]\\(:=\\)"                #Xee0b)
            ("\\(!!\\)"                    #Xee0c)
            ("\\(!=\\)"                    #Xee0d)
            ("\\(!==\\)"                   #Xee0e)
            ("\\(-}\\)"                    #Xee0f)
            ("\\(--\\)"                    #Xee10)
            ("\\(---\\)"                   #Xee11)
            ("\\(-->\\)"                   #Xee12)
            ("[^-]\\(->\\)"                #Xee13)
            ("\\(->>\\)"                   #Xee14)
            ("\\(-<\\)"                    #Xee15)
            ("\\(-<<\\)"                   #Xee16)
            ("\\(-~\\)"                    #Xee17)
            ("\\(#{\\)"                    #Xee18)
            ("\\(#\\[\\)"                  #Xee19)
            ("\\(##\\)"                    #Xee1a)
            ("\\(###\\)"                   #Xee1b)
            ("\\(####\\)"                  #Xee1c)
            ("\\(#(\\)"                    #Xee1d)
            ("\\(#\\?\\)"                  #Xee1e)
            ("\\(#_\\)"                    #Xee1f)
            ("\\(#_(\\)"                   #Xee20)
            ("\\(\\.-\\)"                  #Xee21)
            ("\\(\\.=\\)"                  #Xee22)
            ("\\(\\.\\.\\)"                #Xee23)
            ("\\(\\.\\.<\\)"               #Xee24)
            ("\\(\\.\\.\\.\\)"             #Xee25)
            ("\\(\\?=\\)"                  #Xee26)
            ("\\(\\?\\?\\)"                #Xee27)
            ("\\(;;\\)"                    #Xee28)
            ("\\(/\\*\\)"                  #Xee29)
            ("\\(/\\*\\*\\)"               #Xee2a)
            ("\\(/=\\)"                    #Xee2b)
            ("\\(/==\\)"                   #Xee2c)
            ("\\(/>\\)"                    #Xee2d)
            ("\\(//\\)"                    #Xee2e)
            ("\\(///\\)"                   #Xee2f)
            ("\\(&&\\)"                    #Xee30)
            ("\\(||\\)"                    #Xee31)
            ("\\(||=\\)"                   #Xee32)
            ("[^|]\\(|=\\)"                #Xee33)
            ("\\(|>\\)"                    #Xee34)
            ("\\(\\^=\\)"                  #Xee35)
            ("\\(\\$>\\)"                  #Xee36)
            ("\\(\\+\\+\\)"                #Xee37)
            ("\\(\\+\\+\\+\\)"             #Xee38)
            ("\\(\\+>\\)"                  #Xee39)
            ("\\(=:=\\)"                   #Xee3a)
            ("[^!/]\\(==\\)[^>]"           #Xee3b)
            ("\\(===\\)"                   #Xee3c)
            ("\\(==>\\)"                   #Xee3d)
            ("[^=]\\(=>\\)"                #Xee3e)
            ("\\(=>>\\)"                   #Xee3f)
            ("\\(<=\\)"                    #Xee40)
            ("\\(=<<\\)"                   #Xee41)
            ("\\(=/=\\)"                   #Xee42)
            ("\\(>-\\)"                    #Xee43)
            ("\\(>=\\)"                    #Xee44)
            ("\\(>=>\\)"                   #Xee45)
            ("[^-=]\\(>>\\)"               #Xee46)
            ("\\(>>-\\)"                   #Xee47)
            ("\\(>>=\\)"                   #Xee48)
            ("\\(>>>\\)"                   #Xee49)
            ("\\(<\\*\\)"                  #Xee4a)
            ("\\(<\\*>\\)"                 #Xee4b)
            ("\\(<|\\)"                    #Xee4c)
            ("\\(<|>\\)"                   #Xee4d)
            ("\\(<\\$\\)"                  #Xee4e)
            ("\\(<\\$>\\)"                 #Xee4f)
            ("\\(<!--\\)"                  #Xee50)
            ("\\(<-\\)"                    #Xee51)
            ("\\(<--\\)"                   #Xee52)
            ("\\(<->\\)"                   #Xee53)
            ("\\(<\\+\\)"                  #Xee54)
            ("\\(<\\+>\\)"                 #Xee55)
            ("\\(<=\\)"                    #Xee56)
            ("\\(<==\\)"                   #Xee57)
            ("\\(<=>\\)"                   #Xee58)
            ("\\(<=<\\)"                   #Xee59)
            ("\\(<>\\)"                    #Xee5a)
            ("[^-=]\\(<<\\)"               #Xee5b)
            ("\\(<<-\\)"                   #Xee5c)
            ("\\(<<=\\)"                   #Xee5d)
            ("\\(<<<\\)"                   #Xee5e)
            ("\\(<~\\)"                    #Xee5f)
            ("\\(<~~\\)"                   #Xee60)
            ("\\(</\\)"                    #Xee61)
            ("\\(</>\\)"                   #Xee62)
            ("\\(~@\\)"                    #Xee63)
            ("\\(~-\\)"                    #Xee64)
            ("\\(~=\\)"                    #Xee65)
            ("\\(~>\\)"                    #Xee66)
            ("[^<]\\(~~\\)"                #Xee67)
            ("\\(~~>\\)"                   #Xee68)
            ("\\(%%\\)"                    #Xee69)
            ;;("\\(x\\)"                     #e6b)
            ("[^:=]\\(:\\)[^:=]"           #Xee6a)
            ("[^\\+<>]\\(\\+\\)[^\\+<>]"   #Xee6b)
            ("[^\\*/<>]\\(\\*\\)[^\\*/<>]" #Xee6c))))

(defun add-fira-code-symbol-keywords ()
  (font-lock-add-keywords nil fira-code-font-lock-keywords-alist))

(add-hook 'prog-mode-hook
          #'add-fira-code-symbol-keywords)
